name: Publish release
run-name: Publish release ${{ github.event.release.tag_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - fork

jobs:
  publish:
    name: "Publish release"
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Test version
        id: version
        run: |
          version=$(cat lib/build.gradle.kts | grep -E 'version = "' | cut -d \" -f 2)
          if git show-ref --tags --quiet --verify -- "refs/tags/$version" >/dev/null; then
            echo "Git tag $version already exists, failing to publish";
            exit 1
          else
            echo "release_tag=$version" >> $GITHUB_OUTPUT
          fi

      - name: Setup JDK
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Cache konan directory
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: "${{ runner.os }}-konan-"

      - name: Build and Maven 'publish'
        run: |
          if [ -n "$GH_TOKEN" ]; then
            echo "GH_TOKEN is set. Running publish script."
            bash ./publish.sh
          else
            echo "GH_TOKEN is missing. Bailing out."
            exit 1
          fi